# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Learner.one_batch": "00_core.ipynb",
         "unrar": "00_core.ipynb",
         "extract_frames": "00_core.ipynb",
         "avi2frames": "00_core.ipynb",
         "get_instances": "00_core.ipynb",
         "Path.ls_sorted": "00_core.ipynb",
         "ImageTuple": "00_core.ipynb",
         "ImageTupleTfm": "00_core.ipynb",
         "get_action_dataloaders": "00_core.ipynb",
         "Encoder": "01_models.ipynb",
         "SimpleModel": "01_models.ipynb",
         "simple_splitter": "01_models.ipynb",
         "LSTM": "01_models.ipynb",
         "ConvLSTM": "01_models.ipynb",
         "convlstm_splitter": "01_models.ipynb",
         "TimeSformer": "01_models.ipynb",
         "STAM": "01_models.ipynb"}

modules = ["core.py",
           "models.py"]

doc_url = "https://tcapelle.github.io/action_recognition/"

git_url = "https://github.com/tcapelle/action_recognition/tree/master/"

def custom_doc_links(name): return None
