# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"PATH": "00_core.ipynb",
         "Path.BASE_PATH": "00_core.ipynb",
         "IMAGE_PATH": "00_core.ipynb",
         "SPLIT_PATH": "00_core.ipynb",
         "get_sequence_paths": "00_core.ipynb",
         "ImageTuple": "00_core.ipynb",
         "ImageTupleBlock": "00_core.ipynb",
         "get_tuple_files": "00_core.ipynb",
         "make_sequences": "00_core.ipynb",
         "sort_files": "00_core.ipynb",
         "ActionDataset": "00_core.ipynb",
         "TupleImage": "00_core.ipynb",
         "ImageTupleTfm": "00_core.ipynb",
         "get_split": "00_core.ipynb",
         "get_split_idxs": "00_core.ipynb",
         "get_action_dataloaders": "00_core.ipynb",
         "grand_parent_label": "00_core.ipynb",
         "get_block": "00_core.ipynb",
         "Encoder": "03_models.ipynb",
         "SimpleModel": "03_models.ipynb",
         "simple_splitter": "03_models.ipynb",
         "LSTM": "03_models.ipynb",
         "ConvLSTM": "03_models.ipynb",
         "convlstm_splitter": "03_models.ipynb",
         "DETR": "03_models.ipynb",
         "detr_split": "03_models.ipynb"}

modules = ["core.py",
           "models.py"]

doc_url = "https://tcapelle.github.io/action_recognition/"

git_url = "https://github.com/tcapelle/action_recognition/tree/master/"

def custom_doc_links(name): return None
